-- 2026-09-04 — Jody's cron-planetanttheatre.js still hasn't written a single
-- row (confirmed live: zero events with source ilike '%planet ant%' /
-- title ilike '%uncaged%' before this script runs). The maxDuration:60 fix
-- shipped earlier tonight is unconfirmed — Vercel Cron may simply not have
-- fired again since, or something else is still wrong; we don't have
-- Vercel log access to be sure. Jody wants "Nicolas Uncaged" (and the rest
-- of Planet Ant's calendar) live now rather than waiting on that cron to
-- sort itself out, so — same move as tonight's STD x 313.electronics post:
-- get the real data in by hand instead of waiting on the automation.
--
-- Unlike that STD post, this ISN'T going through /api/submit — that only
-- gives us a pending_review row with no external_id, city, or the venue's
-- own trust tier. Instead this is a manual one-time run of the exact same
-- transform cron-planetanttheatre.js does (stripCategoryPrefix, mapCategory,
-- parseVenue, minCostDollars, formatTime12h — all reproduced from that
-- file), pulled live from CrowdWork's public API
-- (https://www.crowdwork.com/api/v2/planetanttheatre/shows) just now: every
-- show currently posted for Ant Hall + Black Box, one row per date, 10 shows
-- / 53 rows total, including "Nicolas Uncaged 11" on 2026-09-11.
--
-- Each external_id matches EXACTLY what the cron itself would generate
-- (crowdwork-planetanttheatre-<show id>-<date>) and status is 'approved'
-- (DEFAULT_STATUS, same trust tier as cron-lagerhouse.js — Planet Ant's own
-- official box office). That means once the cron actually starts running
-- successfully, it will upsert cleanly onto these same rows (same
-- on_conflict target) instead of creating duplicates, and will pick up any
-- NEW shows Planet Ant posts after this. This is a one-time catch-up, not a
-- replacement for fixing the cron — worth checking Vercel's logs for
-- cron-planetanttheatre's next scheduled run whenever you get a chance.
--
-- Image URLs below have their CDN query-string suffix stripped (confirmed
-- live that the bare URL still loads fine — looked like a cache-busting
-- token, not an auth token).

insert into events (external_id, title, description, category, venue_name_raw, venue_address_raw, venue_city_raw, start_date, time_display, note, is_free, price_from, image_url, ticket_url, source, status)
values
  ('crowdwork-planetanttheatre-16814-2026-09-04', 'Lilith''s Big Ol'' Golden Show presents: Femmes To the Front!', '"Femmes To the Front" is the newest installment of Lilith''s Big Ol'' Golden Show! This show could have easily been called "Big Diva Energy" or "One Big Room Full of Bad B*tches", but no matter what it''s called, this show is a rejection of the male...', 'nightlife', 'Ant Hall', '2320 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-04', '8:00 PM', NULL, false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16814/Femmes_to_the_front_Final.png', 'https://www.crowdwork.com/e/burlesque-l-lilith-s-big-ol-golden-show-presents-femmes-to-the-front', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-09-07', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-07', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-09-14', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-14', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-09-21', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-21', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-09-28', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-28', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-10-05', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-10-05', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-10-12', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-10-12', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-10-19', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-10-19', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-10-26', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-10-26', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-11-02', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-11-02', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-11-09', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-11-09', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-11-16', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-11-16', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-11-23', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-11-23', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-11-30', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-11-30', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16212-2026-12-07', 'Monday Night Improv w/ The Planet Ant Home Team', 'Every Monday night, the Black Box stage brings the longest-running improv show in Detroit— a fresh, new, and hilarious night of comedy from the legendary Planet Ant Home Team. Each week features opening performances from The Planet Ant Farm Team a...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-12-07', '7:30 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16212/A_J.png', 'https://www.crowdwork.com/e/improv-l-monday-night-improv-w-the-planet-ant-home-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-09-10', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-10', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-09-17', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-17', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-09-24', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-24', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-10-01', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-10-01', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-10-08', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-10-08', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-10-15', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-10-15', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-10-22', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-10-22', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-10-29', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-10-29', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-11-05', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-11-05', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-11-12', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-11-12', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-11-19', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-11-19', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-11-26', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-11-26', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-12-03', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-12-03', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-12-10', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-12-10', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16271-2026-12-17', 'The Thursday Show w/ The Planet Ant Farm Team', 'The Thursday Show is Planet Ant''s weekly live variety night, featuring original sketch comedy, improv, character bits, and guest performers. Every show is created fresh and performed live, with a rotating monthly theme that ties each night togethe...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-12-17', '8:00 PM', 'Entrance in the rear', false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16271/610268392_18554571001059777_654537386631628407_n.jpg', 'https://www.crowdwork.com/e/comedy-l-the-thursday-show-w-the-planet-ant-farm-team', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-17181-2026-09-11', 'The Good Enough Club', 'Experience a raw, intimate one-act drama that strips away the romanticism of the tortured artist. Gale Greenwood is a promising and ambitious young painter who pushes themselves to get their work displayed at a highly anticipated art exhibition ...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-11', '8:00 PM', 'Entrance in the rear', false, 6.59, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/17181/September_11th_-_26th__1_.png', 'https://www.crowdwork.com/e/theatre-l-the-good-enough-club', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-17181-2026-09-12', 'The Good Enough Club', 'Experience a raw, intimate one-act drama that strips away the romanticism of the tortured artist. Gale Greenwood is a promising and ambitious young painter who pushes themselves to get their work displayed at a highly anticipated art exhibition ...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-12', '8:00 PM', 'Entrance in the rear', false, 6.59, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/17181/September_11th_-_26th__1_.png', 'https://www.crowdwork.com/e/theatre-l-the-good-enough-club', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-17181-2026-09-13', 'The Good Enough Club', 'Experience a raw, intimate one-act drama that strips away the romanticism of the tortured artist. Gale Greenwood is a promising and ambitious young painter who pushes themselves to get their work displayed at a highly anticipated art exhibition ...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-13', '3:00 PM', 'Entrance in the rear', false, 6.59, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/17181/September_11th_-_26th__1_.png', 'https://www.crowdwork.com/e/theatre-l-the-good-enough-club', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-17181-2026-09-18', 'The Good Enough Club', 'Experience a raw, intimate one-act drama that strips away the romanticism of the tortured artist. Gale Greenwood is a promising and ambitious young painter who pushes themselves to get their work displayed at a highly anticipated art exhibition ...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-18', '8:00 PM', 'Entrance in the rear', false, 6.59, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/17181/September_11th_-_26th__1_.png', 'https://www.crowdwork.com/e/theatre-l-the-good-enough-club', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-17181-2026-09-19', 'The Good Enough Club', 'Experience a raw, intimate one-act drama that strips away the romanticism of the tortured artist. Gale Greenwood is a promising and ambitious young painter who pushes themselves to get their work displayed at a highly anticipated art exhibition ...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-19', '8:00 PM', 'Entrance in the rear', false, 6.59, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/17181/September_11th_-_26th__1_.png', 'https://www.crowdwork.com/e/theatre-l-the-good-enough-club', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-17181-2026-09-20', 'The Good Enough Club', 'Experience a raw, intimate one-act drama that strips away the romanticism of the tortured artist. Gale Greenwood is a promising and ambitious young painter who pushes themselves to get their work displayed at a highly anticipated art exhibition ...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-20', '3:00 PM', 'Entrance in the rear', false, 6.59, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/17181/September_11th_-_26th__1_.png', 'https://www.crowdwork.com/e/theatre-l-the-good-enough-club', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-17181-2026-09-25', 'The Good Enough Club', 'Experience a raw, intimate one-act drama that strips away the romanticism of the tortured artist. Gale Greenwood is a promising and ambitious young painter who pushes themselves to get their work displayed at a highly anticipated art exhibition ...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-25', '8:00 PM', 'Entrance in the rear', false, 6.59, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/17181/September_11th_-_26th__1_.png', 'https://www.crowdwork.com/e/theatre-l-the-good-enough-club', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-17181-2026-09-26', 'The Good Enough Club', 'Experience a raw, intimate one-act drama that strips away the romanticism of the tortured artist. Gale Greenwood is a promising and ambitious young painter who pushes themselves to get their work displayed at a highly anticipated art exhibition ...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-26', '8:00 PM', 'Entrance in the rear', false, 6.59, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/17181/September_11th_-_26th__1_.png', 'https://www.crowdwork.com/e/theatre-l-the-good-enough-club', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-17073-2026-09-11', 'Nicolas Uncaged 11', 'T.G.I.F.! Hop on your Razor scooter and IM all your BFFs because we''re back to spice up your life for a UnCaged first: a Y2K-ified mostly pre-9/11 celebration in honor of our one true god, Nicolas Cage, while also paying tasteful respects to those...', 'film', 'Ant Hall', '2320 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-11', '8:00 PM', NULL, false, 32.85, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/17073/image0__2_.jpeg', 'https://www.crowdwork.com/e/film-l-nicolas-uncaged-11', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16270-2026-09-12', 'Mixtape Friendship 5000', 'Welcome to the Mixtape Friendship 5000 where each month we''ll have a friendly music related discussion that kicks off comedy from veteran Detroit Improvisors along with a killer opening group. Your songs become the show! The first Saturday of ever...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-12', '10:30 PM', 'Entrance in the rear', false, 8.69, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16270/545159770_10109614010213518_4783487218962295589_n.jpg', 'https://www.crowdwork.com/e/improv-l-mixtape-friendship-5000', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16270-2026-10-03', 'Mixtape Friendship 5000', 'Welcome to the Mixtape Friendship 5000 where each month we''ll have a friendly music related discussion that kicks off comedy from veteran Detroit Improvisors along with a killer opening group. Your songs become the show! The first Saturday of ever...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-10-03', '10:30 PM', 'Entrance in the rear', false, 8.69, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16270/545159770_10109614010213518_4783487218962295589_n.jpg', 'https://www.crowdwork.com/e/improv-l-mixtape-friendship-5000', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16270-2026-11-07', 'Mixtape Friendship 5000', 'Welcome to the Mixtape Friendship 5000 where each month we''ll have a friendly music related discussion that kicks off comedy from veteran Detroit Improvisors along with a killer opening group. Your songs become the show! The first Saturday of ever...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-11-07', '10:30 PM', 'Entrance in the rear', false, 8.69, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16270/545159770_10109614010213518_4783487218962295589_n.jpg', 'https://www.crowdwork.com/e/improv-l-mixtape-friendship-5000', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16270-2026-12-05', 'Mixtape Friendship 5000', 'Welcome to the Mixtape Friendship 5000 where each month we''ll have a friendly music related discussion that kicks off comedy from veteran Detroit Improvisors along with a killer opening group. Your songs become the show! The first Saturday of ever...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-12-05', '10:30 PM', 'Entrance in the rear', false, 8.69, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16270/545159770_10109614010213518_4783487218962295589_n.jpg', 'https://www.crowdwork.com/e/improv-l-mixtape-friendship-5000', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16270-2027-01-02', 'Mixtape Friendship 5000', 'Welcome to the Mixtape Friendship 5000 where each month we''ll have a friendly music related discussion that kicks off comedy from veteran Detroit Improvisors along with a killer opening group. Your songs become the show! The first Saturday of ever...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2027-01-02', '10:30 PM', 'Entrance in the rear', false, 8.69, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16270/545159770_10109614010213518_4783487218962295589_n.jpg', 'https://www.crowdwork.com/e/improv-l-mixtape-friendship-5000', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16270-2027-02-06', 'Mixtape Friendship 5000', 'Welcome to the Mixtape Friendship 5000 where each month we''ll have a friendly music related discussion that kicks off comedy from veteran Detroit Improvisors along with a killer opening group. Your songs become the show! The first Saturday of ever...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2027-02-06', '10:30 PM', 'Entrance in the rear', false, 8.69, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16270/545159770_10109614010213518_4783487218962295589_n.jpg', 'https://www.crowdwork.com/e/improv-l-mixtape-friendship-5000', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16270-2027-03-06', 'Mixtape Friendship 5000', 'Welcome to the Mixtape Friendship 5000 where each month we''ll have a friendly music related discussion that kicks off comedy from veteran Detroit Improvisors along with a killer opening group. Your songs become the show! The first Saturday of ever...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2027-03-06', '10:30 PM', 'Entrance in the rear', false, 8.69, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16270/545159770_10109614010213518_4783487218962295589_n.jpg', 'https://www.crowdwork.com/e/improv-l-mixtape-friendship-5000', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16270-2027-04-03', 'Mixtape Friendship 5000', 'Welcome to the Mixtape Friendship 5000 where each month we''ll have a friendly music related discussion that kicks off comedy from veteran Detroit Improvisors along with a killer opening group. Your songs become the show! The first Saturday of ever...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2027-04-03', '10:30 PM', 'Entrance in the rear', false, 8.69, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16270/545159770_10109614010213518_4783487218962295589_n.jpg', 'https://www.crowdwork.com/e/improv-l-mixtape-friendship-5000', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16270-2027-05-01', 'Mixtape Friendship 5000', 'Welcome to the Mixtape Friendship 5000 where each month we''ll have a friendly music related discussion that kicks off comedy from veteran Detroit Improvisors along with a killer opening group. Your songs become the show! The first Saturday of ever...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2027-05-01', '10:30 PM', 'Entrance in the rear', false, 8.69, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16270/545159770_10109614010213518_4783487218962295589_n.jpg', 'https://www.crowdwork.com/e/improv-l-mixtape-friendship-5000', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-16270-2027-06-05', 'Mixtape Friendship 5000', 'Welcome to the Mixtape Friendship 5000 where each month we''ll have a friendly music related discussion that kicks off comedy from veteran Detroit Improvisors along with a killer opening group. Your songs become the show! The first Saturday of ever...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2027-06-05', '10:30 PM', 'Entrance in the rear', false, 8.69, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/16270/545159770_10109614010213518_4783487218962295589_n.jpg', 'https://www.crowdwork.com/e/improv-l-mixtape-friendship-5000', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-17276-2026-09-20', 'Take a Detroit Tour. Support Planet Ant!', 'One of our very own improvisors, Robyn, also happens to be a Detroit tour guide! She''s hosting a special walking tour of downtown Detroit, with all proceeds benefiting Planet Ant Theatre. Come explore Detroit, discover some places you may have wal...', 'community', 'MEETING LOCATION: Guardian Building', NULL, NULL, '2026-09-20', '2:00 PM', NULL, false, 32.85, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/17276/walking_tour.jpg', 'https://www.crowdwork.com/e/take-a-detroit-tour-support-planet-ant', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-17415-2026-09-23', 'Buck''s Funhouse', 'Buck''s Funhouse! Get ready for an electrifying LIVE experience that combines the excitement of a game show with the intimate energy of a podcast. Filmed live for the internet, the show features music from the Funhouse Band, "Lee Cleaveland and The...', 'theatre', 'Ant Hall', '2320 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-09-23', '7:30 PM', NULL, false, 11.84, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/17415/Bucks_Funhouse-2160.jpg', 'https://www.crowdwork.com/e/game-show-l-buck-s-funhouse', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-17569-2026-10-22', 'Shortbus 20th Anniversary Live Commentary Screening w/ John Cameron Mitchell', 'Join John Cameron Mitchell in celebrating the 20th anniversary of his groundbreaking film “SHORTBUS” with a live in-person commentary screening featuring behind the scenes stories of the making of the film! The evening will end with a Q&A and musi...', 'community', 'Ant Hall', '2320 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-10-22', '7:00 PM', NULL, false, 38.1, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/17569/JCMmatthewPlacekHIRESglitter.jpg', 'https://www.crowdwork.com/e/shortbus-20th-anniversary-live-commentary-screening-w-john-cameron-mitchell', 'Planet Ant Theatre', 'approved'),
  ('crowdwork-planetanttheatre-17328-2026-11-28', 'Nate Varrone', 'An evening of stand-up comedy with Nate Varrone as he embarks on the Midwest leg of his "Interesting Perspectives" Tour. Nate is a filmmaker, stand-up comedian, actor, and TV writer living in Los Angeles, CA. He is an alum of The Second City Mains...', 'theatre', 'Black Box', '2357 Caniff, Hamtramck, MI 48212', 'Hamtramck', '2026-11-28', '8:00 PM', 'Entrance in the rear', false, 22.35, 'https://cdn.fourthwalltickets.com/uploads/event/imgs/17328/Nate_Varrone.png', 'https://www.crowdwork.com/e/standup-comedy-l-nate-varrone', 'Planet Ant Theatre', 'approved')
on conflict (external_id) do update set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  venue_name_raw = excluded.venue_name_raw,
  venue_address_raw = excluded.venue_address_raw,
  venue_city_raw = excluded.venue_city_raw,
  start_date = excluded.start_date,
  time_display = excluded.time_display,
  note = excluded.note,
  is_free = excluded.is_free,
  price_from = excluded.price_from,
  image_url = excluded.image_url,
  ticket_url = excluded.ticket_url,
  source = excluded.source;
-- NOTE: status intentionally NOT in the update-set list, matching the
-- cron's own status-preserving upsert (an admin's approve/reject on an
-- existing row survives future runs) -- see cron-planetanttheatre.js.
