-- Sets image_url for the 9 RA pull-6 events from their flyer uploads.
-- Generated by upload-ra-pull6-flyers.sh -- run in Supabase's SQL editor.

update events set image_url = 'https://afvyfjfqukptnfmgshzn.supabase.co/storage/v1/object/public/event-flyers/a5c5b773-ba97-4ba9-9573-2e3602ebaf63.webp' where external_id = 'ra-2533991'; -- LATIN NIGHT: DJ IZA & SWDJEY
update events set image_url = 'https://afvyfjfqukptnfmgshzn.supabase.co/storage/v1/object/public/event-flyers/7a4d0136-ac24-4156-91eb-5a171ec46380.webp' where external_id = 'ra-2529033'; -- Club 1BD
update events set image_url = 'https://afvyfjfqukptnfmgshzn.supabase.co/storage/v1/object/public/event-flyers/47c9099d-2ba7-48a6-89b4-d1b615ddb489.webp' where external_id = 'ra-2533789'; -- RIDDIM RESTAURANT
update events set image_url = 'https://afvyfjfqukptnfmgshzn.supabase.co/storage/v1/object/public/event-flyers/07c6e282-a12a-41a6-8c97-8444a902b5fe.webp' where external_id = 'ra-2539083'; -- G.E.D.: Ghettotech, Electro and DrumN'Bass
update events set image_url = 'https://afvyfjfqukptnfmgshzn.supabase.co/storage/v1/object/public/event-flyers/b5616699-4fc5-470a-aa07-3ea1c2df4725.webp' where external_id = 'ra-2538279'; -- NICE TIME
update events set image_url = 'https://afvyfjfqukptnfmgshzn.supabase.co/storage/v1/object/public/event-flyers/dfe306a8-45b2-4682-b963-39a9280693c2.webp' where external_id = 'ra-2526339'; -- Hottie's World
update events set image_url = 'https://afvyfjfqukptnfmgshzn.supabase.co/storage/v1/object/public/event-flyers/74f7efa8-5ad0-4c9a-9e35-cd7af72f3230.webp' where external_id = 'ra-2525346'; -- DJ Rozwell - Detroit
update events set image_url = 'https://afvyfjfqukptnfmgshzn.supabase.co/storage/v1/object/public/event-flyers/68458a8f-411c-4f71-b5a9-d3b936399f29.webp' where external_id = 'ra-2517135'; -- Ms. Nina with SWDEJAY and Psy-Chick
update events set image_url = 'https://afvyfjfqukptnfmgshzn.supabase.co/storage/v1/object/public/event-flyers/67cbfcdf-9fab-4eda-9978-6c278827300a.webp' where external_id = 'ra-2532522'; -- 12 Hour Party


insert into schema_migrations (filename) values ('update_2026-09-18_ra-pull6-images.sql')
on conflict (filename) do nothing;
