-- 20261006000000_baseline_schema.sql
--
-- BASELINE: the application schema as it exists in PRODUCTION on 2026-10-06,
-- reconstructed from the production catalog (schema only; no row data was
-- read). It replaces layering migration_002..045 + schema.sql, which could not
-- rebuild production (missing migration_010, two 042s, DDL inside data patches,
-- and migrations never applied to production). The historical files stay in
-- supabase/ unchanged as a record; see supabase/migrations/README.md.
--
-- Mirrors production faithfully, INCLUDING its known gaps, so staging behaves
-- like production:
--   * event_category has 14 values and NO 'gaming' (BUG-008; fix is proposed in
--     supabase/proposed/, to be applied to staging first).
--   * No sources table / events.source_id / venues.venue_type (migration_004
--     was never applied to production), no Facebook columns on events.
--   * Table grants: this file creates tables only. The broad privileges
--     production has (anon/authenticated/service_role = ALL) are stated
--     explicitly in 20261006000002_baseline_grants.sql as the LEGACY PRODUCTION
--     BASELINE; Row Level Security is then the only gate on public tables.
--     Hardening is SZ-01, a later migration.
--
-- Do not edit this file after it has been applied anywhere; add a new
-- migration instead.

-- ---------------------------------------------------------------- enums
create type event_category as enum ('music','theatre','dance','visual','museum','family','fest','food','film','nightlife','sports','community','vendor','training');
create type event_status as enum ('pending_review','approved','rejected');
create type feed_format as enum ('ics','rss','manual');
create type feed_status as enum ('pending_review','approved','rejected','paused');
create type neighborhood_confidence_level as enum ('geographic','multi_source','single_source','editorial_judgment','unconfirmed');
create type editorial_match_type as enum ('title','venue_date','manual');

-- ------------------------------------------------------------ functions
create or replace function set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- --------------------------------------------------------------- tables
create table categories (
  id          uuid primary key default gen_random_uuid(),
  slug        text not null unique,
  label       text not null,
  color_var   text,
  sort_order  integer not null,
  created_at  timestamptz not null default now()
);

create table neighborhoods (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique,
  area_note   text,
  is_district boolean not null default false,
  created_at  timestamptz not null default now()
);

create table organizers (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  description text,
  website     text,
  instagram   text,
  type        text,
  image_url   text,
  created_at  timestamptz not null default now()
);
create unique index organizers_name_key on organizers (lower(name));

create table venues (
  id                      uuid primary key default gen_random_uuid(),
  name                    text not null,
  address                 text,
  city                    text not null default 'Detroit',
  website                 text,
  lat                     double precision,
  lng                     double precision,
  created_at              timestamptz not null default now(),
  neighborhood_id         uuid references neighborhoods(id) on delete set null,
  zip_code                text,
  neighborhood_confidence neighborhood_confidence_level not null default 'unconfirmed',
  neighborhood_source     text,
  instagram_url           text,
  facebook_url            text,
  tiktok_url              text,
  twitter_url             text
);
create unique index venues_name_city_key on venues (lower(name), lower(city));
create index venues_name_lower_idx on venues (lower(trim(both from name)));

create table feed_sources (
  id                 uuid primary key default gen_random_uuid(),
  venue_name         text not null,
  contact_email      text not null,
  website            text,
  feed_url           text not null,
  feed_format        feed_format not null default 'ics',
  default_category   event_category not null,
  notes              text,
  status             feed_status not null default 'pending_review',
  last_polled_at     timestamptz,
  last_poll_result   text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  location_per_event boolean not null default false
);
create unique index feed_sources_url_key on feed_sources (lower(feed_url));
create index feed_sources_status_idx on feed_sources (status);

create table events (
  id                      uuid primary key default gen_random_uuid(),
  title                   text not null,
  description             text,
  category                event_category not null,
  venue_id                uuid references venues(id) on delete set null,
  venue_name_raw          text,
  start_date              date not null,
  end_date                date,
  time_display            text,
  is_recurring            boolean not null default false,
  is_free                 boolean not null default false,
  price_from              numeric(10,2),
  ticket_url              text,
  image_url               text,
  source                  text not null default 'Manual',
  note                    text,
  status                  event_status not null default 'approved',
  submitter_org_name      text,
  submitter_email         text,
  external_id             text,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),
  organizer_id            uuid references organizers(id) on delete set null,
  neighborhood_id         uuid references neighborhoods(id) on delete set null,
  neighborhood_confidence neighborhood_confidence_level not null default 'unconfirmed',
  neighborhood_source     text,
  venue_city_raw          text,
  feed_source_id          uuid references feed_sources(id) on delete set null,
  venue_address_raw       text,
  event_url               text,
  category_id             uuid references categories(id) on delete set null,
  followup_dismissed      boolean not null default false,
  followup_dismissed_note text,
  followup_dismissed_at   timestamptz,
  internal_note           text,
  is_all_day              boolean not null default false,
  ticket_status           text,
  is_clothing_optional    boolean not null default false,
  description_source      text,
  no_fixed_venue          boolean not null default false,
  link_check_status       text,
  link_checked_at         timestamptz,
  constraint events_description_source_check
    check (description_source is null or description_source = any (array['manual','authoritative','generated']))
);
create unique index events_external_id_key on events (external_id);
create index events_category_id_idx on events (category_id);
create index events_category_idx on events (category);
create index events_feed_source_id_idx on events (feed_source_id);
create index events_neighborhood_id_idx on events (neighborhood_id);
create index events_source_idx on events (source);
create index events_start_date_idx on events (start_date);
create index events_status_idx on events (status);
create index events_status_start_date_idx on events (status, start_date);
create index events_venue_id_idx on events (venue_id);
create index events_venue_name_raw_lower_idx on events (lower(trim(both from venue_name_raw)));

create table editorial_articles (
  id               uuid primary key default gen_random_uuid(),
  source           text not null,
  feed_url         text not null,
  title            text not null,
  excerpt          text,
  url              text not null,
  thumbnail_url    text,
  published_at     timestamptz,
  matched_event_id uuid references events(id) on delete set null,
  match_type       editorial_match_type,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  admin_dismissed  boolean not null default false
);
create unique index editorial_articles_url_key on editorial_articles (url);
create index editorial_articles_matched_event_id_idx on editorial_articles (matched_event_id);
create index editorial_articles_published_at_idx on editorial_articles (published_at);
create index editorial_articles_admin_review_idx on editorial_articles (published_at desc)
  where matched_event_id is null and admin_dismissed = false;

create table editorial_article_events (
  article_id uuid not null references editorial_articles(id) on delete cascade,
  event_id   uuid not null references events(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (article_id, event_id)
);
create index editorial_article_events_event_id_idx on editorial_article_events (event_id);

create table event_source_identities (
  event_id   uuid not null references events(id) on delete cascade,
  source     text not null,
  source_id  text not null,
  created_at timestamptz not null default now(),
  primary key (source, source_id)
);
create index event_source_identities_event_id_idx on event_source_identities (event_id);

create table healthchecks (
  id          uuid primary key default gen_random_uuid(),
  run_at      timestamptz not null default now(),
  overall     text not null,
  duration_ms integer,
  checks      jsonb not null default '[]'::jsonb,
  created_at  timestamptz not null default now(),
  constraint healthchecks_overall_check check (overall = any (array['ok','fail']))
);
create index healthchecks_run_at_idx on healthchecks (run_at desc);

create table schema_migrations (
  filename   text primary key,
  applied_at timestamptz not null default now(),
  note       text
);

create table source_runs (
  id              uuid primary key default gen_random_uuid(),
  source_slug     text not null,
  started_at      timestamptz not null default now(),
  finished_at     timestamptz,
  outcome         text not null default 'started',
  http_status     integer,
  records_fetched integer,
  records_parsed  integer,
  records_written integer,
  error_sample    text,
  duration_ms     integer,
  session_data    jsonb,
  constraint source_runs_outcome_check check (outcome = any (array['started','success','partial','failed','blocked']))
);
create index source_runs_source_slug_started_at_idx on source_runs (source_slug, started_at desc);
create index source_runs_started_outcome_idx on source_runs (started_at) where outcome = 'started';

-- ------------------------------------------------------------- triggers
create trigger editorial_articles_set_updated_at before update on editorial_articles for each row execute function set_updated_at();
create trigger events_set_updated_at before update on events for each row execute function set_updated_at();
create trigger feed_sources_set_updated_at before update on feed_sources for each row execute function set_updated_at();

-- ----------------------------------------------------------------- view
-- Owner-rights view (no security_invoker), as in production: it serves only
-- approved rows and a fixed column list.
create view events_public as
 select e.id, e.title, e.description, e.image_url, e.start_date, e.end_date, e.time_display,
        e.category, e.is_free, e.price_from, e.source, e.note, e.ticket_url, e.event_url, e.venue_id,
        coalesce(v.name, e.venue_name_raw) as venue_name,
        coalesce(v.city, e.venue_city_raw) as venue_city,
        n.name as neighborhood,
        e.is_clothing_optional, e.ticket_status
   from events e
   left join venues v on v.id = e.venue_id
   left join neighborhoods n on n.id = v.neighborhood_id
  where e.status = 'approved';

-- ---------------------------------------------------------- RLS + policies
alter table categories               enable row level security;
alter table editorial_article_events enable row level security;
alter table editorial_articles       enable row level security;
alter table event_source_identities  enable row level security;
alter table events                   enable row level security;
alter table feed_sources             enable row level security;
alter table healthchecks             enable row level security;
alter table neighborhoods            enable row level security;
alter table organizers               enable row level security;
alter table schema_migrations        enable row level security;
alter table source_runs              enable row level security;
alter table venues                   enable row level security;

create policy "public read categories"               on categories               for select using (true);
create policy "public read editorial article events" on editorial_article_events for select using (true);
create policy "public read editorial articles"       on editorial_articles       for select using (true);
create policy "public read approved events"          on events                   for select using (status = 'approved');
create policy "public submit pending events"         on events                   for insert with check (status = 'pending_review');
create policy "public submit pending feed sources"   on feed_sources             for insert with check (status = 'pending_review');
create policy "public read neighborhoods"            on neighborhoods            for select using (true);
create policy "public read organizers"               on organizers               for select using (true);
create policy "public read venues"                   on venues                   for select using (true);
-- event_source_identities, healthchecks, schema_migrations, source_runs:
-- RLS on, no policies (service role only), as in production.

-- Table grants are in 20261006000002_baseline_grants.sql (legacy production
-- baseline). Do not rely on Supabase project defaults: they differ by project age.
grant select on events_public to anon, authenticated;

-- ----------------------------------------------------------------- storage
-- Public bucket for submitted flyers; uploads go through api/upload-image.js
-- with the service role, so no storage policies exist (as in production).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('event-flyers', 'event-flyers', true, 4194304, array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do nothing;
